version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: sh -c "python wait_for_db.py && gunicorn --bind 0.0.0.0:8000 app:app"
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=sistema_conversion
      - POSTGRES_HOST=10.128.0.5
    volumes:
      - /nfs/uploaded-files:/tmp/Sist_Conv_Files_Uploaded
      - /nfs/processed-files:/tmp/Sist_Conv_Files_Processed
  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=sistema_conversion
  redis:
    image: "redis:latest"
    ports:
      - '6379:6379'
  celery:
    build: .
    command: ["python", "/app/wait_for_postgres.py", "&&", "celery", "-A", "celery_worker.celery", "worker", "--loglevel=info"]
    depends_on:
      - web
      - redis
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - /nfs/uploaded-files:/tmp/Sist_Conv_Files_Uploaded
      - /nfs/processed-files:/tmp/Sist_Conv_Files_Processed

volumes:
  uploaded-files:
  processed-files: