version: '3.8'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:8001 app:app
    expose:
      - 8001
    env_file:
      - ./.env.prod
    depends_on:
      - db
  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on:
      - web
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data_prod: